config/routes.rb
Rails.application.routes.draw do
  root :to => 'skills#index'
  resources :skills
  resources :about
  resources :contact
  resources :links

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<div id="content">
  <div id="about">
    <h3>About me:</h3>
    <p>I have a great desire for learning and creating. The web development industry suits me well because of this.
      My other interests include botany, photography, and traveling to far flung places with my family.
      My ultimate goal is to make useful creative things that people will enjoy and pay for.</p>
  </div>
</div>

app/views/contact/index.html.erb
<div id="content">
  <div class="contact-info">
    Phone: <a href="tel:+15125676637">(512) 567-6637</a>
  </div>
  <div class="contact-info">
    Email: <a href="mailto:joshuaatteberry@gmail.com">joshuaatteberry@gmail.com</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Josefin+Sans|Source+Code+Pro:200,400,600' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width" />
  <title>Joshua Atteberry</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="seperation-border">
    <div id="title">
      <span id="my-name"><%= link_to "Joshua Atteberry", skills_path %></span>
      <span id="my-title"><%= link_to "Web Developer", skills_path %></span>
    </div>

    <ul class="nav">
      <li><%= link_to "Skills", skills_path %></li>
      <li><%= link_to "About", about_index_path %></li>
      <li><%= link_to "Contact", contact_index_path %></li>
    </ul>
  </header>

<%= yield %>

  <footer>
    <p>&copy; 2015 Joshua Atteberry.</p>
  </footer>
</body>
</html>

app/views/links/index.html.erb
<div id="links">
  <h1>CSS</h1>
  <ul>
    <li><a href="https://developer.mozilla.org/en-US/docs/Web/CSS/Reference">MDN CSS</a></li>
      <ul>
        <li><a href="https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes">Pseudo classes</a></li>
        <li><a href="https://developer.mozilla.org/en-US/docs/tag/CSS%20Data%20Type">Data types</a></li>
        <li><a href="https://developer.mozilla.org/en-US/docs/Web/CSS/color_value">Color Values</a></li>
        <li><a href="https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type">list-style-type</a></li>
        <li><a href="https://developer.mozilla.org/en-US/docs/Web/CSS/gradient">Gradients</a></li>
        <li><a href="https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face">@font-face</a></li>
        <li><a href="https://developer.mozilla.org/en-US/docs/Web/CSS/letter-spacing">Letter spacing</a></li>
        <li><a href="https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Media_queries">Media queries</a></li>
        <li><a href="https://developer.mozilla.org/en-US/docs/Web/CSS/@media">@media</a></li>
        <li><a href="https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag">Viewport meta tag</a></li>
      </ul>

    <li><a href="http://www.cssfontstack.com/">CSS fonts</a></li>
    <li><a href="http://www.fontsquirrel.com/">Font squirrel</a></li>
    <li><a href="https://docs.webplatform.org/wiki/css">WebPlatform CSS</a></li>
    <li><a href="http://www.w3.org/Style/CSS/Overview.en.html">WS CSS</a></li>
    <li><a href="http://markdotto.com/playground/3d-text/">3D text with just CSS</a></li>
    <li><a href="http://css.maxdesign.com.au/listamatic/horizontal01.htm">Simple horizontal list</a></li>
    <li><a href="http://stackoverflow.com/questions/22592064/how-to-align-text-below-an-image-in-css">How to align text below an image in CSS?</a></li>
    <li><a href="http://stackoverflow.com/questions/6722467/how-to-remove-the-default-link-color-of-the-html-a-tag">how to remove default a tag link color</a></li>
    <li><a href="https://developers.google.com/web/fundamentals/layouts/rwd-fundamentals/use-media-queries?hl=en">Media queries for responsiveness</a></li>
  </ul>

  <h1>Design</h1>
  <ul>
    <li><a href="http://viget.com/inspire/color-contrast">How to pick colors GOOD</a></li>
    <li><a href="https://dribbble.com/">Dribbble</a></li>
    <li><a href="http://www.alexbeeken.com/about/">Alex Beeken's resume site</a></li>
    <li><a href="http://www.amperx.com">A nice portfolio</a></li>
    <li><a href="https://developer.leapmotion.com/">Leap Motion, has some fonts and design that are decent</a></li>
    <li><a href="http://paperjs.org/">PaperJS</a></li>
    <li><a href="http://qcalligraphy.com/typogrid1.0/">Create your own typography</a></li>
  </ul>

  <h1>Rails</h1>
  <li><a href="https://www.railstutorial.org/book/beginning">Rails tutorial book</a></li>
  <li><a href="https://www.ruby-toolbox.com">Ruby toolbox</a></li>
  <li><a href="http://www.gotealeaf.com/blog/how-to-use-devise-in-rails-for-authentication">Devise authentication tutorial</a></li>

  <h1>JavaScript</h1>
  <ul>
    <li><a href="http://jsbin.com/?js,output">JS Bin</a></li>
    <li><a href="https://www.youtube.com/watch?v=PMfcsYzj-9M">Definitive guide to OO Javascript (youtube) Watch this?</a></li>
    <li><a href="http://sbstjn.github.io/timesheet.js/">Timesheet.js</a></li>
  </ul>

  <h1>AngularJS</h1>
  <ul>
    <li><a href="https://thinkster.io/">Thinkster.io</a></li>
    <li><a href="https://thinkster.io/learn-to-build-realtime-webapps/">Build a hacker news like site in angular (thinkster)</a></li>
    <li><a href="http://stackoverflow.com/questions/16660826/show-hidden-div-on-ng-click-within-ng-repeat">Show hidden div on ng-click withing ng-repeat</a></li>
    <li><a href="https://github.com/JakeKaad/minesweeper-js/blob/master/blog.md">"Making sense of angular" (from an epicodus student)</a></li>
  </ul>

  <h1>MeteorJS</h1>
  <li><a href="http://joshowens.me/getting-started-with-meteor-js/">A blogpost about meteor with a bunch of good links</a></li>

  <h1>Jobs</h1>
  <ul>
    <li><a href="http://www.jrdevjobs.com/">Jr Dev Jobs</a></li>
    <li><a href="https://jobs.lever.co/cratejoy/8e4f0355-c24a-48f0-ba7a-ee141e114d00">Cratejoy</a></li>
    <li><a href="https://pdxstartups.switchboardhq.com/">PDX Startups Switchboard</a></li>
    <li><a href="http://www.40digits.com/job/front-end-developer/">40Digits, employer in STL</a></li>
    <li><a href="http://www.wearefine.com/careers/front-end-web-developer">FINE in portland</a></li>
    <li><a href="http://www.forbes.com/sites/dailymuse/2014/11/18/27-pre-written-templates-for-your-toughest-work-emails/">27 Pre-Written Templates For Your Toughest Work Emails</a></li>
    <li><a href="http://www.cdkjobs.com/jobs/view/81582-Software-Engineer?language=en">CDK Usedcars.com</a></li>
    <li>Search Hacker News Who's hiring</li>
    <li><a href="http://jobs.rubynow.com/">Ruby Jobs</a></li>
  </ul>

  <h1>Web hosting</h1>
  <ul>
    <li><a href="https://control205.webhostingforstudents.com:2083/cpsess123977481/frontend/x3/index.html">Webhosting login</a></li>
    <li><a href="http://webhostingforstudents.com/">Web hosting for students</a></li>
    <li><a href="https://www.namecheap.com/">Namecheap domains (look for coupon)</a></li>
  </ul>

  <h1>Orchid site</h1>
  <ul>
    <li><a href="http://www.eyeofscience.de/en/botany/">Orchid seed photo</a></li>
    <li><a href="http://www.amjbot.org/content/102/3.cover-expansion">Journal with an orchid seed cover</a></li>
    <li><a href="http://www.phytesia.com/en/assortment.php?PHPSESSID=57fe966bc7833867780178605b94d03e">Phytesia design example</a></li>
  </ul>

  <h1>Electronics</h1>
  <ul>
    <li><a href="https://www.google.com/search?q=Nema+17&oq=Nema+17&aqs=chrome..69i57.1161j0j7&sourceid=chrome&es_sm=91&ie=UTF-8#q=Nema+17&safe=off&tbm=shop">Nema 17 stepper motor</a></li>
    <li><a href="https://github.com/Seeed-Studio/Sketchbook_Starter_Kit_V2.0">Seeed starter kit github</a></li>
    <li><a href="http://www.instructables.com/id/Intel-IoT-Edison-web-controlled-LED/?ALLSTEPS">Blinking led web app instructable</a></li>
    <li><a href="http://www.codefoster.com/edison-setup/">Setting up edison</a></li>
  </ul>

  <h1>MISC</h1>
  <ul>
    <li><a href="http://www.hongkiat.com/blog/grunt-command-not-found/">Solving "grunt: command not found"</a></li>
    <li><a href="http://www.inaturalist.org/">iNaturalist</a></li>
    <li><a href="https://pcottle.github.io/learnGitBranching/">Interactive way to learn Git</a></li>
    <li><a href="https://try.github.io/levels/1/challenges/1">Another interactive way to learn Git</a></li>
    <li><a href="https://www.firebase.com/account/#/profile">Firebase account page</a></li>
    <li><a href="http://caniuse.com/">Can I Use. Test element compatability in different environments</a></li>
    <li><a href="https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/screen.1.html">Mac Commands</a></li>
    <li><a href="http://www.kinnetica.com/2011/05/29/using-screen-on-mac-os-x/">Screen commands</a></li>
    <li><a href="https://raw.githubusercontent.com/AmyVS/epicodus-cliff-notes/master/README.md">README.md formatting example</a></li>
    <li><a href="http://www.hanselman.com/">Scott Hanselmann Blog</a></li>
    <li><a href="https://www.udacity.com/georgia-tech">Udacity Georgia Tech Computer science</a></li>
  </ul>

  <h1>Reddit threads</h1>
  <ul>
    <li><a href="http://www.reddit.com/r/angularjs/comments/2mh8u1/looking_for_intensive_courses_in_angular/">Angular courses</a></li>
    <li><a href="http://www.reddit.com/r/web_design/comments/27hvg9/could_you_recommend_me_some_frameworks_for_a/">Frameworks for a resume site</a></li>
  </ul>

  <h1>Intel Edison</h1>
  <ul>
    <li><a href="https://learn.sparkfun.com/tutorials/loading-debian-ubilinux-on-the-edison">Installing Ubilinux on edison</a></li>
  </ul>


  <h1>Notes</h1>
  <p>
    March, 3, 15, Contact @eric on Thinkster pro slack channel about jobs. @benstr is the other person I was talking to on the meteorjs channel.
  </p>

  <h1>Really MISC</h1>
  <ul>
    <li><a href="http://www.shopjimmy.com/sanyo-j4he-main-board-for-p42740-00.htm#">part for sanyo tv</a></li>
    <li><a href="http://www.newegg.com/Product/Product.aspx?Item=N82E16813300003">Newegg raspi</a></li>
  </ul>
</div>

app/views/skills/index.html.erb
<div id="content">
  <div class="logo-with-text">
    <img src="img/html5.png" id="html">
    <span class="skill-text">HTML5</span>
  </div>

  <div class="logo-with-text">
    <img src="img/css.png" id="css">
    <span class="skill-text">CSS3</span>
  </div>

  <div class="logo-with-text">
    <img src="img/js.png" id="js">
    <span class="skill-text">JavaScript</span>
  </div>

  <div class="logo-with-text">
    <img src="img/jquery.png" id="jquery">
    <span class="skill-text">jQuery</span>
  </div>

  <div class="logo-with-text">
    <img src="img/angularjs.png">
    <span class="skill-text">AngularJS</span>
  </div>

  <div class="logo-with-text">
    <img src="img/emberjs.png">
    <span class="skill-text">EmberJS</span>
  </div>

  <div class="logo-with-text">
    <img src="img/ruby-on-rails.png">
    <span class="skill-text">Ruby on Rails</span>
  </div>

  <div class="logo-with-text">
    <img src="img/mysql.png" id="mysql">
    <span class="skill-text">MySQL</span>
  </div>

  <div class="logo-with-text">
    <img src="img/postgresql.png">
    <span class="skill-text">PostgreSQL</span>
  </div>
</div>